<a href="https://colab.research.google.com/github/joshz123/Disaster-Tweets/blob/josh/NaiveModel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
!pip install tensorflow==2.0

     |████████████████████████████████| 86.3MB 52kB/s 
     |████████████████████████████████| 450kB 55.4MB/s 
     |████████████████████████████████| 3.8MB 53.2MB/s 
  Found existing installation: tensorflow-estimator 1.15.1
    Uninstalling tensorflow-estimator-1.15.1:
      Successfully uninstalled tensorflow-estimator-1.15.1
  Found existing installation: tensorboard 1.15.0
    Uninstalling tensorboard-1.15.0:
      Successfully uninstalled tensorboard-1.15.0
  Found existing installation: tensorflow 1.15.0
    Uninstalling tensorflow-1.15.0:
      Successfully uninstalled tensorflow-1.15.0


In [0]:
from __future__ import absolute_import, division, print_function, unicode_literals

import tensorflow as tf

from tensorflow.keras.layers import Dense, Flatten, Conv2D
from tensorflow.keras import Model


try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass

print(tf.version)

TensorFlow is already loaded. Please restart the runtime to change versions.
<module 'tensorflow_core._api.v2.version' from '/usr/local/lib/python3.6/dist-packages/tensorflow_core/_api/v2/version/__init__.py'>


Test 1
GRU ->
Linear -> 
Simoid


In [0]:
#to plot loss over time 

import matplotlib.pyplot as plt

def plot_graphs(history, metric):
  plt.plot(history.history[metric])
  plt.plot(history.history['val_'+metric], '')
  plt.xlabel("Epochs")
  plt.ylabel(metric)
  plt.legend([metric, 'val_'+metric])
  plt.show()

In [0]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving new_train_data.txt to new_train_data (1).txt
Saving targets.txt to targets (1).txt
User uploaded file "new_train_data.txt" with length 745718 bytes
User uploaded file "targets.txt" with length 22839 bytes


# New Section

# New Section

In [0]:
tweets = list()
targets = list()

with open('new_train_data.txt', 'r') as f:
  tweets = f.readlines()
print(len(tweets))

with open('targets.txt', 'r') as f:
  targets = f.readlines()
targets2 = list()
for i in range(0, len(targets)): 
    targets2.append(int(targets[i]))
targets = targets2

7613


In [0]:
from tensorflow.keras.preprocessing.text import Tokenizer

max_words = 14000
tokenizer = Tokenizer(num_words=max_words)


In [0]:
trainX = tweets[:6000]
trainY = targets[:6000]

testX = tweets[6000:]
testY = tweets[6000:]

maxlen = 100

from tensorflow.keras.preprocessing.sequence import pad_sequences

tokenizer.fit_on_texts(trainX)
tokenized_version = tokenizer.texts_to_sequences(trainX)
tokenized_version = pad_sequences(tokenized_version, maxlen=maxlen)
print(tokenized_version)

[[   0    0    0 ...  165   58    1]
 [   0    0    0 ...   84   15    1]
 [   0    0    0 ...   33 1064    1]
 ...
 [   0    0    0 ...   10 2164    1]
 [   0    0    0 ...    8  682    1]
 [   0    0    0 ...  866 3316    1]]


In [0]:
vocab_size = 14000
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(vocab_size, 64),
    tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(64, return_sequences=True)),
    tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(64)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(1, activation='softmax')
])

model.compile(loss=tf.keras.losses.BinaryCrossentropy(),
              optimizer=tf.keras.optimizers.Adam(1e-5),
              metrics=['accuracy']) 

In [0]:
import numpy as np
trainY = np.array(trainY)

model.fit(x=tokenized_version, y=trainY, batch_size = 64, epochs=4, validation_split = 0.2)

Train on 4800 samples, validate on 1200 samples
Epoch 1/4
4800/4800 [==============================] - 19s 4ms/sample - loss: 8.9252 - accuracy: 0.4179 - val_loss: 8.8038 - val_accuracy: 0.4258
Epoch 2/4
4800/4800 [==============================] - 15s 3ms/sample - loss: 8.9252 - accuracy: 0.4179 - val_loss: 8.8038 - val_accuracy: 0.4258
Epoch 3/4
1152/4800 [======>.......................] - ETA: 10s - loss: 9.1307 - accuracy: 0.4045